### ISSUE TITLE
编码问题没人遇到过么？

### ISSUE THREAD

**Issue by Skymemory** [istommao/django-simditor#21]
`Traceback (most recent call last):
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/python2.7.12/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/dev/projects/supermarket/supermarket/urls.py", line 32, in <module>
    url(r'^simditor/', include('simditor.urls')),
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/python2.7.12/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/simditor/urls.py", line 10, in <module>
    from . import views
  File "/home/vagrant/.supermarket/lib/python2.7/site-packages/simditor/views.py", line 42

SyntaxError: Non-ASCII character '\xe5' in file /home/vagrant/.supermarket/lib/python2.7/site-packages/simditor/views.py on line 42, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

views.py文件中用了中文，但没申明编码方式，大家的都不报错么？

**Comment by istommao** [comment]
python2没测试过 你可以用 python3 试试 @Skymemory

**Comment by Skymemory** [comment]
> python2没测试过 你可以用 python3 试试 @Skymemory

嗯，python 3可以
