### ISSUE TITLE
在centos6下安装, Python3.6 报错

### ISSUE THREAD

**Issue by SilvesSun** [istommao/django-simditor#8]
`Collecting django-mdeditor
  Using cached https://files.pythonhosted.org/packages/e2/19/7623e00aa1eafc4c68ecff13a03505cfee003b9e8bd2350e8c6f28cc52d1/django-mdeditor-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qbbpxwl5/django-mdeditor/setup.py", line 5, in <module>
        README = readme.read()
      File "/root/.virtualenvs/blogWithDjango2/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3255: ordinal not in range(128)
`

**Comment by istommao** [comment]
![image](https://user-images.githubusercontent.com/5070879/40397550-e90f546e-5e65-11e8-9c31-a45c8223296d.png)
不是很清楚 你怎么操作的，我 3.6 安装正常

**Comment by SilvesSun** [comment]
sorry. 我先自己检查下.
